version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[analyzers]]
name = "secrets"

[[analyzers.meta]]
  skip_doc_coverage = ["class-expression", "method-definition"]
